### ISSUE TITLE
The observation in Combined Arms

### ISSUE THREAD

**Issue by LXXXXR** [Farama-Foundation/MAgent2#42]
Hi,

Thank you for maintaining this fantastic repository. I have a quick question regarding the documentation for `Combined Arms`. In the documentation(https://magent2.farama.org/environments/combined_arms/#observation-space), `Other teams presences/heaths/minimaps` feature in the observation space is described as being "in some order".  Could you please clarify what this order is? 

Thank you!

**Comment by atstarke** [comment]
Hi @LXXXXR , I think this listed this way because its dependent on the agent type. Each type red_melee, red_Ranged, blue_melee, and blue_ranged are registered within the environment as g0, g1, g2, g3 respectfully. So the observations for: red_ranged (g1) would be:
Red Melee (g0): Presence → Health → Minimap (if enabled)
Blue Melee (g2): Presence → Health → Minimap (if enabled)
Blue Ranged (g3): Presence → Health → Minimap (if enabled)

With presence, health, and Minimap each being a channel and the Minimap being optional, that is why this can be 6/9 channels deep.

I hope this helps!

If you find something to the contrary, please let me know!

**Comment by LXXXXR** [comment]
Thank you so much for the prompt reply! It really helps!
